version: '3.8'

services:
  product-service:
    restart: always
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    volumes:
      - ./product-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  review-service:
    restart: always
    container_name: review-service
    build:
      context: ./review-service
      dockerfile: Dockerfile
    volumes:
      - ./review-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001

  api-gateway:
    restart: always
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000